export const BARANGAY_LIST = [
  { id: '1', name: 'Agua Dulce', code: 'AGD' },
  { id: '2', name: 'Bayan', code: 'BAY' },
  { id: '3', name: 'Buhangin', code: 'BUH' },
  { id: '4', name: 'Calulut', code: 'CAL' },
  { id: '5', name: 'Capayawan', code: 'CAP' },
  { id: '6', name: 'Cruz', code: 'CRZ' },
  { id: '7', name: 'Dalagdut', code: 'DAL' },
  { id: '8', name: 'Del Pilar', code: 'DLP' },
  { id: '9', name: 'Florang', code: 'FLR' },
  { id: '10', name: 'Gomez', code: 'GOM' },
  { id: '11', name: 'Mabini', code: 'MAB' },
  { id: '12', name: 'Macarse', code: 'MAC' },
  { id: '13', name: 'Magsaysay', code: 'MAG' },
  { id: '14', name: 'Masin', code: 'MAS' },
  { id: '15', name:'Matagtag', code: 'MTG' },
  { id: '16', name: 'Poblacion', code: 'PBL' },
  { id: '17', name: 'San Jose', code: 'SJO' },
  { id: '18', name: 'San Juan', code: 'SJ' },
  { id: '19', name: 'San Nicolas', code: 'SNL' },
  { id: '20', name: 'Santa Rosa', code: 'SRT' },
] as const;